---
nSpecies: 4

species:
  so2:
    molarMass: 0.064
    heatCapacityModel: polynomial
    enthalpyFormation: -296860.220
    entropyFormation: 248.100
    heatCapacityCoefficients: [3.53]

  o2:
    molarMass: 0.032
    heatCapacityModel: polynomial
    enthalpyFormation: 0.0
    entropyFormation: 205.00
    heatCapacityCoefficients: [3.53]

  n2:
    molarMass: 0.028
    heatCapacityModel: polynomial
    enthalpyFormation: 0.0
    entropyFormation: 191.00
    heatCapacityCoefficients: [3.53]

  so3:
    molarMass: 0.080
    heatCapacityModel: polynomial
    enthalpyFormation: -395780.300
    entropyFormation: 256.6
    heatCapacityCoefficients: [3.53]

reactions:
  so2_conversion:
    isReversible: true
    ahrreniusPreExponent: 2.5e10
    ahrreniusActivationEnergy: 165000.0
    stochiometricCoefficients: [-1.0, -0.5, 0.0, 1.0]
    speciesExponent: [1.0, 0.5, 0.0, 0.0]
    reversedSpecieExponent: [0.0, 0.0, 0.0, 1.0]

mixture:
  densityModel: ideal-incompressible-gas
  densityValue: null